uc-cdis/gen3-qa

.gitignore, Dockerfile, Jenkinsfile, README.md, apis/presignedUrlTest.js, apis/userTokenTest.js, cdisHelper.js, codecept.json, package.json, portal/homepageTest.js, questions/homepageDetails.js, run-tests.sh, steps/fenceAPI.js, steps/homepage.js, steps/loginGoogle.js, stepsFile.js
In this pull request, I did
- install `codeceptjs` that use `WebdriverIO` as test runner.
- write homepage test and fence test for testing presigned-url and user token.
- test steps are written in `steps` folder
- details things to test are written in `questions` folder
- `portal` folder contains all tests for portal
- `apis` folder contains all tests for REST apis
- running test needs `ACCESS_TOKEN`, `INDEX_USERNAME`, `INDEX_PASSWORD` environment variables.
- then, just run `npm install` and `npm run test`
r @philloooo  @frickjack @giangbui
=> feat(init): first steps, test homepage

test_setup.js, utils/commonsUtil.js
There is an occasional error in test_setup in function trying to create the program project, where the response and error were both undefined, and we'd throw an error because we were trying to check `response.statusCode`.
* added additional check to see if response is undefined before looking at status code
* added method in test_setup for attempting to create program/project multiple times
=> refactor(test_setup): add multiple tries for program/project creation

suites/apis/googleServiceAccountTest.js
The test "Register SA that looks like its from the Google Project but doesnt actually exist" in "googleServiceAccountTest.js" randomly fails on PRs that have nothing to do with fence. Disable it until fixed
=> fix(dcf-test): disable failing test

README.md, helpers/cdisHelper.js, services/portal/home/homeProps.js, services/portal/home/homeQuestions.js, services/portal/home/homeSequences.js, services/portal/home/homeTasks.js, suites/portal/dataUploadTest.js, suites/portal/homepageTest.js
Fixes a bug where a test logs in, doesn't log out, and the following tests fail because they don't find the login button
- do not set an `access_token` to log in at the beginning of the tests
- log in and log out using the portal buttons before and after each windmill test
=> fix(login-logout): remove default login; add logout logic

services/portal/home/homeQuestions.js
Checking that the homepage contains exactly 4 `.index-button-bar__thumbnail-button` elements (the boxes `Define Data Field`, `Access Data` etc) makes the tests fail on cdis-manifest PRs for commons that don't have exactly 4 boxes, for example CVB:
Checking that at least 1 box is there should be enough to make sure the page has loaded
=> fix(homepage-test)

services/apis/fence/fenceTasks.js, suites/apis/googleServiceAccountTest.js
This test will run up to 5 times in case of failure
Also add logs to registerGoogleServiceAccount() to help debug: prints the contents of the JSON response that describes the errors during registration.
=> fix(inexistent-sa-test): add log and retry

services/apis/pidgin/pidginQuestions.js, suites/apis/getCoremetadataTest.js
Peregrine version earlier than 1.0.8 makes pidgin fail - add an error log to the pidgin test to help catch it and debug
=> fix(pidgin-log)

suites/apis/submitAndQueryNodesTest.js
This was fixed in https://github.com/uc-cdis/peregrine/pull/124
I think removing this test from here is our best option:
- if we re-enable it, integration tests for cdis-manifest PRs on commons that are not using the latest version of peregrine will fail
- it's basically a copy of the unit test i'm adding to peregrine, it's not really an integration test, it adds no coverage
=> chore(bool-filter): remove boolean filter test

suites/apis/linkGoogleAccountTest.js
disable flaky "link an acct to a user that already has a linked acct" test until we fix it
=> chore(disable-flaky-test)

run-tests.sh, suites/apis/dataUploadTest.js
The multipart upload feature is in fence 2.8.2 but there is a fix to the error handling that is in fence 3.0.0. So in 2.8.2, the feature works but if the multipart upload fails, the user will see 500 instead of the expected error code. So the integration test `Data file upload flow - Failed multipart upload: wrong ETag for completion` fails.
Fence 3.0.0 can only be deployed at the same time as the other centralized auth updates, so commons that need the multipart upload but not the centralized auth use fence 2.8.2.
=> disable the failing test for fence < 3.0.0
=> fix(multipart)

services/portal/home/homeProps.js
The login test looks for a `h1-typo` element which is **not** displayed on the portal when `components.index.introduction.heading` is set to `""` in the portal config, which is the case for some commons
=> look for `introduction` element instead
=> fix(login)

services/apis/sheepdog/sheepdogProps.js, services/apis/sheepdog/sheepdogQuestions.js, suites/apis/submitAndQueryNodesTest.js
Before sheepdog's integration with arborist, the error is "Authentication Error: Signature has expired" and it's in body.message
After, the error is "request to arborist failed: error decoding token: expired at time: 1567720295" and it's in body.error
This works for both cases
=> fix(auth-error): handle both pre- and post-arborist

codecept.conf.js, package.json
With this configuration in place, a command like this one:
```
% GEN3_SKIP_PROJ_SETUP=true RUNNING_LOCAL=true GEN3_COMMONS_HOSTNAME=gen3.datastage.io npm test -- --verbose --grep '@dataClientCLI|@reqGoogle' --invert suites/apis/dataStageOIDCFlowTest.js
```
Generates a new file under the `output` folder:
e.g., `output/6c4bce71-49ae-44e4-b3e6-d0d9f3d08eaa-testsuite.xml`
Containing all results from all the scenarios that have been tested.
To see the results in a Web GUI just run:
```
gen3-qa [test_allure] % allure serve output/6c4bce71-49ae-44e4-b3e6-d0d9f3d08eaa-testsuite.xml
Generating report to temp directory...
Report successfully generated to /var/folders/d8/qbg4jp1n3b1csgfdlql4qjlr0000gn/T/4941358701907850194/allure-report
Starting web server...
..
Server started at …
```
=> chore(reporting): Enabling allure to capture output for local executable tests

getAccessToken.js, getAccessToken.sh, utils/apiUtil.js, utils/env.js
Tweaking the existing `getAccessToken.sh` script to call a new script: `getAccessToken.js`.
This new script invokes a new lib function: `getAccessTokenFromApiKey ` (which will also be used by executable tests).
Test run:
```
% /bin/bash getAccessToken.sh ~/.gen3/credentials.json
...
access_token: eyJ0eX***
```
=> chore(getAccessTokenInJS): Adding a js util script to fetch access tokens

codecept.conf.js, suites/pre-release/dcf/1.linkAccountsTest.js, suites/pre-release/dcf/prereq.md
First set of executable tests for DCF.
List of DCF Staging test scenarios (as per https://github.com/uc-cdis/cdis-wiki/blob/master/qa/reports/2019/11/DcfStaging-20191114.md):
**--> 1. Bootstrapping accounts (linking Google account)**
2. User Managed Service Accounts
3. Google Credentials
4. Signed URLs
5. OAuth2/OIDC-flow/Client-Testing
6. Indexd
=> task(dcf): Executable tests for DCF: linking Google account scenarios

suites/google/googleServiceAccountKeyTest.js
Looks like we are not failing-fast when it comes it some Google-service-account tests.
Here's one of the util classes we use in the integration tests:
```
async deleteServiceAccount(serviceAccountID, projectID = null) {
...
cloudResourceManager.projects.serviceAccounts.delete(request, (err, res) => {
if (err) {
resolve(Error(err));
return;
}
resolve(res.data);
});
}));
},
```
which is called from `suites/google/googleServiceAccountKeyTest.js`:
```
await google.deleteServiceAccountKey(key.name);
```
even if the function returns an Error object, we don't handle that.
Which leads to failures in the subsequent steps.
We need to fail fast to speed up the debugging process in case of any intermittent issues.
=> chore(integration): Failing fast when google svc account cant be deleted

services/apis/fence/fenceProps.js, services/apis/fence/fenceTasks.js
Small changes to the core gen3-qa lib to support a couple of DCF Staging test scenarios.
I've tested these changes with the following verification script:
https://gist.github.com/themarcelor/1d976784bb29c15d621f0dd61a4cddf2
The test was successful.
Placing this in a small PR to monitor the results of the fully-automated / integration tests executed against other PRs.
=> chore(DCFTests): Tweak lib to support svc acct registration dry run and Google monitor tests

suites/google/googleServiceAccountKeyTest.js
Setting correct name to determine the status of the `google-manage-keys` pod.
Currently, it can't find the pod:
```
Running command: gen3 job run google-manage-keys-job -w 
[32mINFO: 22:12:50 -[39m filtering /var/jenkins_home/workspace/GitHub_Org_cdis-manifest_PR-1045/cloud-automation/kube/services/jobs/google-manage-keys-job.yaml with /var/jenkins_home/workspace/GitHub_Org_cdis-manifest_PR-1045/cdis-manifest/jenkins-brain.planx-pla.net/manifest.json
[32mINFO: 22:12:52 -[39m waiting for google-manage-keys to finish
Error from server (NotFound): jobs.batch "google-manage-keys-job" not found
```
Other commits will be added soon.
=> chore(debug): Improve debugging / logging to investigate flaky tests

run-tests.sh, suites/apis/dbgapTest.js
The DataSTAGE release PRs that are created for the internal staging manifest have been presenting false positives as not all Google-related tests are being executed.
Related to JIRA: https://ctds-planx.atlassian.net/browse/PXP-5155
=> chore(stage): Enable Google tests for internal staging

run-tests.sh
The pipeline needs to be aware of which environments require google integration tests.
Adding the recently introduced URL for DataSTAGE internal staging:
preprod.gen3.biodatacatalyst.nhlbi.nih.gov
=> chore(qa): Enable Google tests for new stage preprod .gov url

run-tests.sh
The version comparison logic from the `runTestsIfServiceVersion` function is not calculating versions properly. This is triggering tests that are not meant to be executed against old Sheepdog versions.
e.g.,
```
RUNNING @indexRecordConsentCodes tests b/c sheepdog version (1.1.6) is greater than 1.1.13
```
From: https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS%20GitHub%20Org%2Fcdis-manifest/detail/PR-1173/1/tests/
=> chore(qa): Fix logic that compares versions within runTestsIfServiceVersion

suites/google/googleDataAccessTest.js
Google data access tests are presenting intermittent failures again.
This is a provisional measure to, potentially, unblock critical PRs.
=> chore(qa): Adding more retries for Google Data Access test while we investigate its flakyness

services/apis/fence/fenceProps.js, suites/google/googleServiceAccountTest.js
Tweaking the assertion for now (since the test still confirms an invalid account can't be registered) -- That should buy us time to continue the debugging without blocking other PRs.
=> chore(qa): Apply temp fix to unblock the pipeline

suites/google/googleServiceAccountTest.js
Adding logging line to check the output of the request that attempts to register a google service account from a project that doesn't have the fence monitor account configured.
This scenario is intermittently producing a weird error:
```Error
expected NaN not to be NaN
Stacktrace
expected NaN not to be NaNAssertionError: expected NaN not to be NaN
at Assertion.<anonymous> (node_modules/chai/lib/chai/core/assertions.js:789:10)```
=> chore(qa): Improve debugging for intermittent NaN assertion + retries

run-tests.sh, suites/apis/drsEndpointsTest.js
Every PR check will try to run the latest gen3-qa automation which now includes the newly introduced DRS tests, however, the endpoints are only enabled on indexd >= 2.8.0.
=> fix(DRS): Only execute DRS tests if Indexd version is greater than 2.8.0

hooks/test_results.js, run-tests.sh
Leverage CodeceptJS hooks to check if DRS endpoints are enabled in the environment and SKIP the tests if the feature is not in place.
=> chore(qa): Skip DRS tests if DRS is not deployed

jenkins-simulate-data.sh
legacy pip3:
```root@4fcf820f9c68:/# which pip3
/usr/bin/pip3
```
New pip3:
```
jenkins@jenkins-deployment-997f489d6-rkk77:~/workspace/CDIS_GitHub_Org_gen3-qa_PR-279/gen3-qa$ which pip3
/var/jenkins_home/.local/bin/pip3
```
Tested here:
```
jenkins@jenkins-deployment-997f489d6-rkk77:~/workspace/CDIS_GitHub_Org_gen3-qa_PR-279/gen3-qa$ /usr/bin/pip3 install cdislogging
...Successfully built cdislogging
Installing collected packages: cdislogging
Successfully installed cdislogging-1.0.0
```
=> fix(qa): data-simulator should use /usr/bin/pip3

run-tests.sh
Enable google tests for cdis-manifests PRs that target the BDCat prod environment:
`gen3.biodatacatalyst.nhlbi.nih.gov/manifest.json`
=> chore(qa): Enable Google tests for BDCat PROD

run-tests.sh
We must run Google integration tests against TheAnvil `cdis-manifest` PRs.
=> chore(qa): Enable Google tests for TheAnvil environments

Jenkinsfile, run-tests.sh
Looks like Jenkins doesn't like empty strings as default values.
Causing failures:
```
StackTrace:
hudson.AbortException: aborting build - testsuite failed
at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:63)
at org.jenkinsci.plugins.workflow.steps.ErrorStep$Execution.run(ErrorStep.java:50)
at org.jenkinsci.plugins.workflow.steps.SynchronousStepExecution.start(SynchronousStepExecution.java:38)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
at groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1278)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1172)
at …
```
=> fix(qa): Set default value for selectedTest

hooks/test_results.js
We are facing several issues due to long-running tests and expired access tokens.
This change will help us benchmark and investigate the root cause.
=> chore(qa): Add timestamp to test.finished hook to assist with debugging

run-tests.sh
Cannot add `--grep @reqGoogle` for all tests because that is suppressing some of the test runs.
=> fix(qa): Apply @reqGoogle only if the tag is found

check-pod-health.sh, run-tests.sh
Currently dataguids.org PRs fail on:
```
+ bash ./check-pod-health.sh
Health https://jenkins-niaid.planx-pla.net/api/_status             : 000
Health https://jenkins-niaid.planx-pla.net/peregrine/_status       : 000
Health https://jenkins-niaid.planx-pla.net/                        : 200
Health https://jenkins-niaid.planx-pla.net/user/jwt/keys           : 000
Health localhost:4444/wd/hub/sessions                              : 200
script returned exit code 1
```
This PR introduces a custom health check logic that verifies only indexd, portal and selenium.
=> chore(qa): Custom health check for dataguids.org

utils/user.js
increase token timeout to accommodate long running jobs
=> chore(token timeout): to 7200 secs

run-tests.sh
Two tests that are not meant to be executed are failing consistently:
1. Data file upload flow: File upload and download via client @dataClientCLI @dataUpload – File upload and download via client @dataClientCLI @dataUpload
2. Data file upload flow File upload with consent codes @dataUpload @indexRecordConsentCodes – File upload with consent codes @dataUpload @indexRecordConsentCodes
As per:
```
#
#
donot '@dataClientCLI'
```
https://github.com/uc-cdis/gen3-qa/blob/master/run-tests.sh#L212
=> fix(qa): Skip @dataClientCLI for dataUpload labeled tests

run-tests.sh, suites/fail.js
This is required to address the issue where some bad labels could be accidentally set and skip all tests.
=> chore(qa): Fail PR Check if Zero tests are executed

README.md, check-pod-health.sh, codecept.conf.js
Innovation day project.
This PR contains changes to adjust documentation and to set all `gen3-qa` tests to run against Selenium Hub.
Tests running on Selenium Hub
The `codecept.conf.js` script is now pointing to the k8s service `selenium-hub`
This should address the flakyness around Selenium/Webdriver operations:
To get rid of errors such as
> chrome not reachable (Session info: headless chrome=70.0.3538.77) (Driver info: chromedriver=2.43.600233
The selenium side car defined in the jenkins deployment YAMl should, eventually, be decommissioned. 
You will only be able to run tests locally if you edit your `/etc/hosts` file to point `selenium-hub` to `127.0.0.1`.
=> chore(qa): Introduce Selenium hub

run-tests.sh
The test is being executed for `cdis-manifest` PRs whose environments do not have a valid `data-portal` version.
=> fix(qa): Only run indexing tests if data-portal >= 2.26.0

run-tests.sh, suites/portal/dataUploadTest.js
PRs labeled with `test-portal-dataUploadTest` are running an executable tests:
```
Did the test pass Y|n ? ls: cannot access 'output/result*.xml': No such file or directory
cat: 'output/result*.xml': No such file or directory
```
`@manual` tests are not supposed to run within Jenkins.
=> chore(qa): Skip @manual test if it is running inside Jenkins

suites/portal/indexingPageTest.js
Setting TSV headers according to the expected DIRM specs:
```
GUID	md5	file_size	acl	authz	urls
```
This change requires https://github.com/uc-cdis/gitops-qa/pull/549
=> task(qa): Improve Manifest Indexing test to comply with DIRM specs.

run-tests.sh
PRs that do not declare the manifest indexing sower jobs are failing:
```
++ /usr/bin/kubectl --namespace=jenkins-brain get cm manifest-sower -o yaml
Error from server (NotFound): configmaps "manifest-sower" not found
+ checkForPresenceOfManifestIndexingSowerJob=
```
This change should suppress the immediate failure caused by the non-zero return code produced by the `grep` command.
=> fix(qa): Suppress bash failures to grep the manifest-indexing configmap

suites/portal/indexingPageTest.js
Renaming tsv header to avoid this error:
```
qa-dcp@cdistest_dev_admin:~$ kc logs manifest-indexing-jdlch-s7x68
Start to index the manifest ...
Start the process ...
Progress: 100.0%
Traceback (most recent call last):
File "manifest_indexing_job.py", line 76, in <module>
write_csv(output_manifest, files, headers)
File "/gen3/utils.py", line 57, in write_csv
writer.writerow(f)
File "/usr/local/lib/python3.6/csv.py", line 155, in writerow
return self.writer.writerow(self._dict_to_list(rowdict))
File "/usr/local/lib/python3.6/csv.py", line 151, in _dict_to_list
+ ", ".join([repr(x) for x in wrong_fields]))
ValueError: dict contains fields not in fieldnames: 'size'
```
=> fix(qa): Quick fix to unblock indexing GUI tests

utils/commanders/sshk8s.js
fix for:
```
bash: gen3: command not found
bash: g3kubectl: command not found
```
=> fix(qa): Fixing Gen3 CLI/PATH after Ubuntu 18 upgrade

suites/apis/centralizedAuth.js
According to the logs, all the centralized auth tests are passing but the test keeps failing due to the `After` clean-up logic.
There seems to be an issue with the number of indexd records and HTTP requests produced to delete the plethora of indexd records created by the tests. This change should changes the flow of the test so it will run the clean-up logic inside the scenarios as opposed to the After block to see if that helps (since we have retries within each scenario).
=> chore(qa): CentralizedAuth - Move indexd records deletion to each scenario

README.md, docker-compose-test-infra.yaml
Test infra needed to run the automated tests locally - selenium, influxdb, grafana. Bring these up with a single command - `docker-compose -f docker-compose-test-infra.yaml up -d`
=> docker compose to bring up test infra locally

.pre-commit-config.yaml, hooks/test_results.js
Switching to test.after hook which is async we are losing information on test retry count since the test teardown starts before this completes. So capturing the value into a variable at the beginning.
=> Missing retry count in influx after switching to test.after

services/apis/fence/fenceTasks.js, utils/google.js
We are still seeing the following error in googleDataAccessTest runs:
```
GoogleDataAccess: Test Google Data Access user0 (signed urls and temp creds) @reqGoogle @googleDataAccess – Test Google Data Access user0 (signed urls and temp creds) @reqGoogle @googleDataAccess
2m 10s
Error
Max number of gstorage api file.get() attempts reached: 4. Expected AccessDenied(403) was never returned.
Stacktrace
```
Hence, increasing the time between the attempts.
=> chore(qa): Wait a bit more for a 403 AccessDenied from Google Storage API call

hooks/test_results.js
To help us identify any issues with CI environments that might be failing consistently / or failing more often than others.
Result:
=> chore(qa): Add selected environment to CI metrics

utils/apiUtil.js
The `.map-chart` element is not displayed when the environment is not set up with a mapbox token. Not sure why this only started failing now
- Fix for COVID19: replace ".map-chart" with ".covid19-dashboard_counts" in homepage test
=> fix for COVID19: .map-chart to .covid19-dashboard_counts

suites/apis/dataStageOIDCFlowTest.js
New code to consider a hadcoded authz only for executable tests executed against TheAnvil environments.
=> chore(qa): Tweak OIDC Testing for TheAnvil

run-tests.sh, services/apis/fence/fenceProps.js
New CI environments might not have unique google cloud project IDs, hence, we need to be able to override the `googleProjectDynamic .id` parameter through an environment variable.
Ideally the mapping of CI environments and their respective unique IDs must be placed in a separate file so we don't end up with multiple IF statements. This code is a short-term solution for to move forward with some experiments in `qaplanetv2`.
=> chore(qa): Allow override of the google dynamic project

run-tests.sh
Disabling a couple of RESTful API & batch processing tests for data-portal PRs to speed up the CI checks for that repo.
=> chore(qa): data-portal PRs should focus on GUI tests

run-tests.sh
=> fix(qa): Do not run RAS tests for fence:2020.08

suites/apis/rasIntegrationTest.js
Addressing items from TODO list:
```
TODO: Run curl with access token and assert the claim is in place
TODO: Check if ga4gh_passport_v1 shows up inside both the aud & scope blocks of the access token
TODO: Check userinfo output (/user/user) using access token in addition to the browser check
TODO: Try to renew the access token through a refresh token
```
=> task(RAS Auth N): Improve aud/scope checks and add refresh token scenario

run-tests.sh
Looks like RAS credentials for test user 1 and 2 mysteriously changed so all RAS tests are failing across the board.
Disabling them temporarily so we can figure this out and re-enable them later.
=> chore(qa): Temporarily disable ras tests due to issues with credentias

run-tests.sh
Enable RAS AuthN tests for:
- `gen3-release` labeled PRs
- `gen3-qa`
- `fence` and 
- `cdis-manifest`
=> chore(qa): Enable RAS tests just for some repos

utils/nodes.js
Every property in `metadata.data` should all have a `submitter_id`.
For some mysterious reason, intermittently, one of the properties under the loop ends up being `null`.
Let us log the whole `metadata` obj along with the warning msg for further debugging.
=> chore(qa): Additional debugging line for the Data File Upload test

suites/batch/GoogleBucketManifestGenerationTest.js, suites/batch/S3BucketManifestGenerationTest.js
The Codeceptjs 3 automation accidentally surrounded the `sort` function arguments with the `{}` notation.
🤦
=> fix(bucket-manifest-ci): fix sort function's syntax

run-tests.sh
Seeing some recurrent failures in a few PRs showing:
```
+ ls output/*-testsuite.xml
ls: cannot access 'output/*-testsuite.xml': No such file or directory
```
This change should improve the error handling to force a proper PR check failure.
=> chore(qa): Better error handling for empty output folder

utils/commanders/sshk8s.js
We need to set the kubeconfig declaration in case we need to override the kubeconfig path (some environments are still using the legacy kubeconfig path instead of adopting the new `Gen3Secrets` folder).
This `export KUBECONFIG` is necessary whenever we are running any of the following scenarios:
- While running a gen3 cli command inside the admin vm  => `(service === undefined)`
- and Running a command inside a kubernetes pod
=> chore(qa): Setting kubeconfig declration accordingly

jenkins-simulate-data.sh
There's no `data_file` node in the midrc DD, so we should use `imaging_data_file` instead.
=> chore(qa): Utilize data simulation with imaging_data_file for PR checks that target midrc environments

hooks/test_results.js
Fixing this error:
```
(node:23173) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
at EventEmitter.<anonymous> (/Users/marcelocostarodrigues/workspace/gen3-qa/hooks/test_results.js:36:15)
```
=> fix(qa): influxDB status nodes check

services/apis/etl/etlSequences.js, suites/apis/etlTest.js
Trying to avoid the intermittent failure that is becoming quite recurrent recently:
```
ETL "after each" hook: finalize codeceptjs for "run ETL second time @etl" – "after each" hook: finalize codeceptjs for "run ETL second time @etl"
<1s
Error
org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: 66987dd54945840faf51e649e311a9d2 
Build info: version: '4.0.0-beta-1', 
revision: '(prerelease)-4610dcfb35' 
System info: host: 'selenium-hub-59dddf6c46-vzkwc', 
ip: '***', 
os.name: 'Linux', 
os.arch: 'amd64', 
os.version: '***', 
java.version: '1.8.0_275' 
Driver info: driver.version: unknown
```
=> chore(qa): Move etl es index checks outside the scenario blocks

suites/portal/landingPageButtonsTest.js
New landing page buttons assertion dictionary:
```
const buttons = [
{
text: 'Learn more',
expectedUrls: ['DD'],
},
{
text: 'Explore data',
expectedUrls: ['explorer', 'files'],
},
{
text: 'Query data',
expectedUrls: ['query'],
},
{
text: 'Run analysis',
expectedUrls: ['workspace'],
},
];
```
=> chore(qa): Both /explorer and /files URLS are valid for the Analyze Data button

suites/apis/etlTest.js, suites/portal/landingPageButtonsTest.js
Our ETL test is based on a background execution of a k8s job (triggered by the `gen3 job run etl` command), which results in an idle thread that pauses everything for longer than 300 seconds, the selenium hub is reaping / terminating our session before the test is completed so CodeceptJS cannot gracefully terminate the session (and that only happens if there’s too much computing based on the size of the dictionary / number of nodes, etc).
This change will avoid the long pause and it will, instead, keep polling the pod for the etl results.
- Improving ETL tests logic to run some polling to check the state of the ETL pod / k8s job.
=> fix(qa): Fix ETL tests

suites/sheepdogAndPeregrine/submitAndQueryNodesTest.js
Address the following failure:
```
SubmitAndQueryNodesTest submit data node with consent codes @indexRecordConsentCodes – submit data node with consent codes @indexRecordConsentCodes
2s
Error
expected [ '/programs/jnkns/projects/jenkins' ] to be a superset of [ '/consents/CC1', '/consents/CC2' ]
Stacktrace
AssertionError: expected [ '/programs/jnkns/projects/jenkins' ] to be a superset of [ '/consents/CC1', '/consents/CC2' ]
at Proxy.<anonymous> (node_modules/chai/lib/chai/core/assertions.js:3094:10)
at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
```
=> fix(qa): Fix logic to run sheepdog test with consent codes

suites/apis/etlTest.js, suites/apis/metadataIngestionTest.js, suites/batch/GoogleBucketManifestGenerationTest.js, suites/batch/S3BucketManifestGenerationTest.js, suites/google/googleDataAccessTest.js, suites/portal/indexingPageTest.js, utils/apiUtil.js
Conditional hack to force the Selenium session to stay alive while polling for k8s job results.
=> fix(qa): Keep Selenium session alive during ETL tests

hooks/test_results.js
No need to gather selenium-hub metrics as the `gen3qa-run` CLI will trigger k8s jobs that will utilize a simple `selenium` side car container.
=> chore(qa): Ignore selenium hub metrics while running in prod

services/portal/home/homeTasks.js
As the MIDRC homepage takes more than 10sec to load, hence causing the tests to fail. 
Now the page will refresh itself
=> fix : fixing the homepage for midrc

suites/batch/S3BucketManifestGenerationTest.js
Quick fix to avoid this error:
```
-- FAILURES:
1) S3 Bucket Manifest Generation
"after each" hook: finalize codeceptjs for "Generate bucket manifest from s3 bucket @amazonS3 @batch @bucketManifest":
unknown error: org.openqa.selenium.NoSuchSessionException: Unable to find session with ID: cb91b4ff5f50d9d78ffbc667b3ea6983
```
=> fix(qa): Bucket Manifest CI must keep the Selenium session alive

suites/portal/dataUploadTest.js
Sometimes the `indexing` pod takes longer to start, so the test is reaching its `checkPod` threshold for some PRs causing intermittent failures.
```
Error
Failed to obtain a successful phase check from the indexing job on attempt 23: Max number of attempts reached: 23
Stacktrace
Error: Failed to obtain a successful phase check from the indexing job on attempt 23: Max number of attempts reached: 23
at checkPod (utils/apiUtil.js:406:15)
at async uploadFile (suites/portal/dataUploadTest.js:48:3)
```
TODO: Find a way to fail fast when the `indexing` pod fails.
=> chore(qa): Increase the number of retries for data upload pod checks

suites/batch/GoogleBucketManifestGenerationTest.js
Prevents the failure below:
```
-- FAILURES:
1) Google Bucket Manifest Generation
"after each" hook: finalize codeceptjs for "Generate bucket manifest from s3 bucket @googleStorage @batch @bucketManifest":
Unable to find handler for (DELETE) /session/63a1b858916c759391289149308f70c2
at Object.getErrorFromResponseBody (node_modules/webdriver/build/utils.js:94:12)
at WebDriverRequest._request (node_modules/webdriver/build/request.js:133:31)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Browser.wrapCommandFn (node_modules/@wdio/utils/build/shim.js:58:29)
```
=> fix(bucket-manifest-test): Keep session alive as Selenium4 kills it after 5 minutes

suites/google/googleServiceAccountKeyTest.js
CodeceptJS 3.0 migration accidentally transformed the `then(object)` code.
=> fix(qa): Fix Google Service Account Key test

hooks/test_results.js, utils/apiUtil.js
We have faced a situation recently where a data file upload test failed due to a missing dependency (`metadata-service` from `ssjdispatcher`). The `checkPod` function kept trying to determine whether or not the `indexing` pod had succeeded but it actually presented a `failed` status, which led the function to, frivolously, continue to check the status of the pod and it led to a situation where the Selenium session got reaped by the Selenium Hub and the test produced a misleading result (It failed silently and returned a ZERO `0` exit code).
This anomaly made 2 PRs turn green misleadingly.
This change improves the polling logic to fail-fast and make an exception bubble up to the Jenkins CDIS Lib groovy caller and force-fail the PR check if any similar issues arise in the future.
=> chore(qa): Improve logic to capture failures with long-running tests and avoid false negatives

jenkins-simulate-data.sh
Adopt python 3.8 in our jenkins-simulate-data.sh script to unblock the data-simulator's `poetry install` command.
=> chore(ci): Adopt python 3.8 in our jenkins-simulate-data.sh script

load-testing/sheepdog/import-clinical-metadata.js
Let us avoid the following failure:
```
time="2021-03-01T17:51:05Z" level=info msg="Request response: {\"code\":400,\"created_entity_count\":0,\"entities\":[{\"action\":\"create\",\"errors\":[{\"keys\":[\"studies\"],\"message\":\"No link destination found for studies, unique_keys='[{'project_id': 'DEV-test', 'submitter_id': 'study_5057ec2ada'}]'\",\"type\":\"INVALID_LINK\"}],\"id\":\"a2a68ca9-14b8-47fd-bd72-8fee462685ea\",\"type\":\"subject\",\"unique_keys\":[{\"project_id\":\"DEV-test\",\"submitter_id\":\"90665063-675c-493d-85ea-094895a548c6\"}],\"valid\":false,\"warnings\":[]}],\"entity_error_count\":1,\"message\":\"Transaction aborted due to 1 invalid entity.\",\"success\":false,\"transaction_id\":19809,\"transactional_error_count\":0,\"transactional_errors\":[],\"updated_entity_count\" …
```
=> chore(load-testing): Select new hardcoded study for sheepdog import script

selenium-wrappers/selenium-node-chrome/Dockerfile, selenium-wrappers/selenium-node-chrome/generate_config
We need to be able to manipulate the `selenium-node-chrome` configuration to achieve verbose logging and even maybe video recording.
- Creating our own gen3-qa-selenium-node-chrome wrapper image.
=> task(ci-debugging): Create wrapper for selenium-node-chrome to manipulate config

scripts/data-manifest-qa-cli.py
Introduce CLI to instrument the gen3 py sdk to run indexing verifications (i.e., that comprises a multi-threaded mechanism that will bombard a target Gen3 Commons environment's INDEXD endpoint and check if every single GUID in a source-of-truth manifest has the correct size, md5 and URL stored correctly in its corresponding indexd record).
- Introduce CLI to instrument the gen3 py sdk to run indexing verifications.
This shall be used by this Jenkins job here: https://github.com/uc-cdis/gen3-release-utils/blob/master/jenkins-jobs/qa-bdcat-data-release-simple-manifest.groovy
=> chore(data-manifest-qa): Introduce indexing manifest QA script

package-lock.json, package.json
Updating the version of node package google-cloud/storage as the current version prevents updating data-and-time package which is highlighted as a security risk by dependabot
=> update version of google cloud storage package

scripts/list-all-test-suites-for-ci.py
This script will help us feed a list of test suites into the parallelization mechanism (Jenkins Groovy logic).
Here's the current output:
```
gen3-qa [chore/introduce_script_to_list_all_test_suites] % python scripts/list-all-test-suites-for-ci.py
Start setup
HOSTNAME: localhost
```
=> chore(test-metadata): Introduce script to list all test suites in label format

suites/apis/etlTest.js
Setting keepSessionAlive to false for ETL tests since no session is created in the test flow
=> set keepSessionAlive to false for etl tests

suites/portal/studyViewerTest.js
fixing the revoke access so that it revokes access naturally depending on what kind of env the tests are running on
```
if (process.env.testedEnv.includes('qa-niaid') || process.env.testedEnv.includes('accessclinicaldata')) {
console.log('### revoking access for user0 in QA/PROD envs ...');
await bash.runCommand(`
revoke access
`);
} else {
console.log('### revoking access for user0 in jenkins env ...');
await bash.runCommand(`
revoke access
`);
}
console.log('### The access is revoked');
```
=> fixing the revoke access in the after suite

run-tests.sh, scripts/list-all-test-suites-for-ci.py, suites/prod/checkAllProjectsBucketAccessTest.js
We should perform the bucket-access-check for both `gs` and `s3` protocols. Not just for Google Buckets.
=> Fix(prod-test): Also scan s3 buckets in access check script

check-pod-health.sh
There is now a commons without portal. So, added logic to prevent portal health check when the service is not deployed
=> donot check portal health when not deployed

Jenkinsfile, suites/guppy/guppyTest.js
We need to be able to mutate the guppy config in our CI environments for 2 test flows:
- DYNAMIC data to test the end-to-end flow of the Export to PFB and Export to Workspace features.
- PREDEFINED data to test Guppy queries based on Queries and Expected Responses (based on Canine DD -- ES index pre-hydrated).
This change takes care of the PREDEFINED test flow.
=> fix(guppy-ci): Mutate guppy config to point to Canine indices before running tests

run-tests.sh
closes #651
- Handle service names with dash in `getServiceVersion`/`runTestsIfServiceVersion`
=> getServiceVersion: handle service names with dash

suites/portal/dataUploadTest.js
We are not fetching the bucket name from config but relying on the standard naming convention. This fixes that.
=> fix bucketname logic

README.md, suites/portal/pfbExportTest.js
The name of the index is not `1520.gitops-qa.jenkins-new_etl` it is actually `1520.gitops-qa.qa-dcp_etl` so this polling logic is wrong because NAMESPACE is `jenkins-new`.
=> fix(pfb-export): Fix polling logic to indentify PR indices

run-tests.sh
- Do not run audit-service tests if fence version is too old
=> Do not run audit-service tests if fence version is too old

suites/portal/pfbExportTest.js
Quick fix due to the current state of the jenkins-ci-worker container:
```
$ docker run -it quay.io/cdis/gen3-ci-worker:master bash
Unable to find image 'quay.io/cdis/gen3-ci-worker:master' locally
master: Pulling from cdis/gen3-ci-worker
...
jenkins@1bf4a1f8a001:~$ python3
bash: python3: command not found
jenkins@1bf4a1f8a001:~$ which python
/usr/bin/python
jenkins@1bf4a1f8a001:~$ /usr/bin/python --version
Python 2.7.16
jenkins@1bf4a1f8a001:~$ python3.8
Python 3.8.0 (default, Jul  9 2021, 23:39:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
=> fix(pfb-export): Run py3.8 for pyPfb parsing assertion

run-tests.sh, suites/guppy/guppyTest.js
Facing intermittent errors:
```
Guppy: I want a list of patients (subjects) strictly younger than 30 with a past stroke in ascending order of BMI. @guppyAPI – I want a list of patients (subjects) strictly younger than 30 with a past stroke in ascending order of BMI. @guppyAPI
<1s
Error
expected 400 to equal 200
```
=> chore(ci): Improve stability of the Guppy test

suites/portal/studyViewerTest.js
@themarcelor's explanation:
`process.env.NAMESPACE`: The environment where the test is running.
`process.env.testedEnv`: The folder from the manifest repo which is utilized to mutate the jenkins env
if jenkins-niaid mutates into these qa-niaid or NCT prod (gitops-qa or cdis-manifest PR), we do NOT want to click the download button
- Study viewer tests: fix references to the current env
=> Study viewer tests: fix references to the current env

suites/portal/pfbExportTest.js
Handling the targetMappingNode
The `submitted_unaligned_reads` node is set by default in pretty much every dictionary (as per the default args in this script: `cloud-automation/blob/master/kube/services/jobs/gentestdata-job.yaml`).
However, if this user flow is running against the Anvil Data Dictionary, the `sequencing` node must be used.
TODO: Look into reusing the leafNode logic from jenkins-simulate-data.sh
=> fix(pfb-export): Refactor logic to use proper targetMappingNode

suites/portal/pfbExportTest.js
Fixing assertion that was set on the wrong assumption the Clinical Data Model hierarchy traversal path  (program -> project -> study) would always be the same.
This test failed recently while running against an environment mutated with `gen3.theanvil.io` artifacts.
```
PFB Export: Install the latest pypfb CLI version and make sure we can parse the avro file @pfbExport – Install the latest pypfb CLI version and make sure we can parse the avro file @pfbExport
1m 44s
Error
expected 'subject' to equal 'study'
Stacktrace
AssertionError: expected 'subject' to equal 'study'
```
ANVIL has program -> project -> subject
BDCAT has program -> project -> study (as originally expected)
There is a need for a better logic to assemble the right assertion around the PFB structure.
=> fix(pfx-export-test): Tweak assertions based on specific Data Dictionaries

run-tests.sh, suites/portal/pfbExportTest.js
Improve the repo checks around the way studyViewer tests are executed.
The studyViewer test should only run in `data-portal, requestor and gen3-qa` service repos and it should run against NCT `gitops-qa` and `cdis-manifest` PR
=> fix(run-test.sh): Improve the studyViewer code

hooks/test_results.js
The old logic is not capturing the configuration correctly:
```
Skipping PFB Export test scenarios since its config does not contain any export-to-pfb buttons...
```
=> fix(pfb-test): Determine presence of export-to-pfb button on Explorer page.

jenkins-simulate-data.sh
Avoid this interruption:
```
curl: (7) Failed to connect to influxdb port 8086: Connection timed out
+ exit 0
ERROR: script returned exit code 7
StackTrace:
hudson.AbortException: script returned exit code 7
at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:659)
at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:605)
at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:549)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) …
```
=> chore(ci): Do not interrupt CI if influxdb is down

services/portal/discovery/discoveryProps.js
`txtDiscoverySearch` now works for both old and new tag/search components in Discovery page
Related PR: https://github.com/uc-cdis/data-portal/pull/927
- `txtDiscoverySearch` now works for both old and new tag/search components in Discovery page
=> fix: disco search bar locator

suites/portal/pfbExportTest.js
Archive temporary .avro file so we can try to reproduce test failures / PFB parsing regressions locally.
=> chore(debug-pfb-export-test): Archive tmp avro file to repro failures

.secrets.baseline, README.md, docker-compose-test-infra-arm64.yaml
Ability to run tests locally Apple M1 machines. The selenium images built for linux/amd64 do not run well on Mac M1's Docker Desktop (emulation mode does not work well, connections to selenium hub are too slow and fail a lot).
=> add support for running tests locally on arm64 processor based machines

suites/portal/pfbExportTest.js
Delete retry for creating new indices to avoid error of index already exists
=> Delete retry for creating new indices in pfbExportTest

suites/apis/requestorTest.js, suites/portal/coremetadatapageTest.js
Don't run corematadatapage tests when pidgin is not deployed
Don't run requestor tests when requestor is not deployed
=> Dont run tests when required service is not deployed

suites/portal/pfbExportTest.js
vpodc dictionary does not have submitted_aligned_reads, so the nightly runs fail
=> use unaligned_reads_file for vpodc in pfbExport

suites/portal/discoveryPageTest.js
- Require `sower` instead of `indexd` for discovery page tests
=> fix: require sower instead of indexd

utils/apiUtil.js
In this nightly build: https://github.com/uc-cdis/cdis-manifest/pull/4752
Multiple pods match the provided label `gen3job`, so the command to check if the job succeeded `g3kubectl get pod <pod name>` is given multiple pod names, so we don't get the job status and we keep waiting for the job to complete long after it's done:
```
waiting for google-manage-keys to finish
waiting for google-manage-keys job pod... - attempt 1
latest pod found: fence-db-migrate-7js8x fence-db-migrate-whm6c fence-db-migrate-29lrn fence-db-migrate-ck98q fence-db-migrate-j6r49 fence-db-migrate-d2mrm gdcdb-create-9ndn8 indexd-userdb-xnbtc fence-db-migrate-kjz9k google-verify-bucket-access-group-x7l2m fence-visa-update-27588990-klnfc gentestdata-bgnfb etl-m4l6t useryaml-dfk8r usersync-2bc9q …
```
=> Fix 'checkPod' logic

suites/apis/aggMDSTest.js
since metadata-aggregate-sync now fails when no data is fetched from adapters
=> commenting out agg mds delete validation

suites/portal/pfbExportTest.js
Nightly build test PFB Export `@requires-portal @e2e Install the latest pypfb CLI version and make sure we can parse the avro file @pfbExport – Install the latest pypfb CLI version and make sure we can parse the avro file @pfbExport` failed twice in a row when using the BDC environment last night and today.
Looks like the cryptography/Rust compiler issue. The test is using Python 3.8 (instead of 3.9, not sure why) but the simple solution is to ensure that we upgrade pip before attempting to install pypfb in the test. I have a PR to do so here: 
```
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 22.3.1 is available.
You should consider upgrading via the …
```
=> fix(install-pypfb): ensure pip is up to date

run-tests.sh
It looks like chromedriver can get updated to support non-stable chrome versions (109 was released which chrome stable version was 108.xx)
=> Get chrome version and use the value to install chromedriver

services/apis/fence/fenceTasks.js, services/apis/peregrine/peregrineTasks.js, suites/coremetadata/getCoremetadataTest.js
- Improve core metadata test errors: check that the request succeeded before checking the fields in the response
=> Improve core metadata test errors

suites/guppy/jenkinsSetup/canineData/arrayMapping.json, suites/guppy/jenkinsSetup/canineData/fileMapping.json, suites/guppy/jenkinsSetup/canineData/subjectMapping.json, suites/guppy/jenkinsSetup/canineData/toyMapping.json
removing the "doc_type" field from the index mapping as ES7 no longer supports it and we are moving Jenkins over to ES7.
=> removing the "doc_type" field 

run-tests.sh
PRs are failing with these tests now. We should test deploying GWAS to environments using a branch with these changes, so reverting the PR until the envs are updated
=> Revert "enabling GWASUi Test for CI checks"

services/apis/sheepdog/sheepdogQuestions.js, suites/apis/dataUploadTest.js, utils/nodes.js
Extract from the logs of failure with IBD dictionary:
```
submit metadata for this file
new metadata.data: {"core_metadata_collections":{"submitter_id":"core_metadata_collection_fullback_Oslo's"},"data_category":"Sequencing Data","data_format":"BAM","data_type":"Unaligned Reads","experimental_strategy":"Validation","file_name":"ash_showpiece's","file_size":77,"md5sum":"446557db934c847ec94d37e4f066f55f","read_groups":{"submitter_id":"read_group_acceptance_fructified"},"submitter_id":"submitted_unaligned_reads_poles_Myrdal","type":"submitted_unaligned_reads","object_id":"aaf97e60-e0b8-49a8-ac93-443fc0e7ce87"}
[succeeds]
[...]
check that we cannot link metadata to a file that already has metadata.
new metadata.data: {"core_metadata_collections":{"submitter_id":"core_metadata_collection_fullba …
```
=> Fix re-submission failure when dictionary does not allow multiple links

run-tests.sh
We should run pfbExport tests in nightly builds but the test run conditions prevent it, so added an extra condition
=> Run pfbExport tests for cdis-manifest

run-tests.sh
Disabling studyViewer tests for now. These tests will be disabled till the automated tests are debugged and running successfully in CI. Suggesting NIAID team to sanity check studyViewer feature manually after the PR is merged in QA (can be done before by deploying versions in QA-NIAID vm). For Pre-Prod and Prod sanity check after the PR is merged.
Ticket to fix the issue - [GQE-211](https://ctds-planx.atlassian.net/browse/GQE-211)
=> disabling studyViewer tests

suites/portal/pfbExportTest.js
=> Fix pfbExportTest
