uc-cdis/gen3-qa

Jenkins/Jenkinsfile

and rename Jenkinsfile, so does not run on PR

fix(Jenkinsfile): enable slack messages

---

Jenkins/Jenkinsfile

fix(archive): add archive

---

Jenkins/Jenkinsfile

until we stabilize the test suite

fix(Jenkinsfile): silent slack notification

---

Jenkins/Jenkinsfile
codecept.json
custom/parameters.js
package.json
run-tests.sh

* don't start the test until the cluster is ready
* generate a test result report

PXD-710 - fix(run-tests.sh): wait for Pending pods

---

steps/coremetadatapage.js
stepsFile.js
suites/portal/coremetadatapageTest.js

PXD-1383 Feat/core metadata

---

assertions/pidginAssertions.js
steps/pidginAPI.js
steps/utilSteps.js
stepsFile.js
suites/apis/getCoremetadataTest.js
suites/apis/submitFileTest.js
suites/apis/utilApis.js

Integration tests for pidgin:
- fetch core metadata using the json endpoint
- fetch core metadata using the bibtex endpoint
- try to fetch core metadata for an invalid file guid
- try to fetch core metadata without permission to access the file

PXD-1264 Feat/pidgin

---

README.md
run-tests.sh
services/apis/indexd/indexdTasks.js
suites/apis/dataUploadTest.js
suites/apis/presignedUrlTest.js

DCF cdis-manifest PR's want Google tests to run

fix(run-tests.sh): enable google for cdis-manifest

---

run-tests.sh
services/apis/etl/etlTasks.js
utils/bash.js
utils/commanders/base.js
utils/commanders/docker.js
utils/dataUploadUtil.js
utils/google.js

* more error checking
* increase timeout
* delete dead code

fix(testfilter): grep/invert confusion

---

run-tests-local.sh
services/apis/etl/etlProps.js
services/apis/etl/etlTasks.js

- minor fixes in the name of the indices

feat(testdata): gen more data for second ETL run

---

jenkins-simulate-data.sh
utils/apiUtil.js
utils/dataUploadUtil.js

pick another data_file node from the dictionary
for data sim if submitted_unaligned_reads
is not there

fix(datasim): no hard-code unaligned_reads

---

run-tests.sh

fix(testedenv-param): change var name

---

test_plans/pidgin/pidgin.feature

I have created a Gherkin feature source file for Pidgin.

Feat/gherkin - Gherkin feature file

---

services/apis/fence/fenceTasks.js
suites/apis/linkGoogleAccountTest.js

fix "link an acct to a user that already has a linked acct"

---

codecept.conf.js
helpers/cdisHelper.js

persistent session cleanup failing in jenkins

fix(selenium): restart session for each test

---

services/apis/fence/fenceQuestions.js
suites/apis/dbgapTest.js

chai.fail should be chai.assert.fail

fix(fail): chai.assert.fail

---

run-tests.sh
suites/apis/dcfDataReplicationTest.js
suites/portal/dashboardReportsTest.js
suites/portal/roleBasedUITest.js

This is an executable test plan for dcf_dataservice data replication service. 
This PR included :
1. AWS sync
2. Google sync
3. check for Updated Indexd

test(dcfreplication): executable test plan added

---

suites/portal/profilePageTest.js
suites/portal/roleBasedUITest.js

interactive test plan for configurable profile page
also add tests to arborist UI test plan for file page "download" button

PXP-4573 Test/arb profile

---

README.md

Minor change to fix the link to the executable tests md file.

chore(readme): Fix link to executable tests page

---

suites/smokeTests/brainTests.js

This PR is to add a smoke test suite into the gen3-qa repo. Also includes executable smoke test plan for brain commons promotion

chore:adding smoke test suite

---

jenkins-simulate-data.sh

Fixed an encoding issue as part of https://github.com/uc-cdis/data-simulator/pull/35 that makes the data-simulator non py2-compatible
- The data-simulator is now python 3, the test pipeline should run it with python 3

Fix: python 3 for data-simulator

---

suites/guppy/tier-access-exclude-sensitive-records-testPlan.md

Resolves PXP-5080: https://ctds-planx.atlassian.net/browse/PXP-5080
- Add test plan for Guppy Tiered Access Sensitive Study Exclusion

Add test plan for Tiered Access Sensitive Study Exclusion

---

services/apis/fence/fenceTasks.js
suites/apis/dbgapTest.js
suites/google/googleDataAccessTest.js
suites/google/googleServiceAccountKeyTest.js
utils/file.js
utils/google.js

Addressing suggestions that @Avantol13 requested on PR https://github.com/uc-cdis/gen3-qa/pull/222.
+ More refactoring and new utils functions to make the tests more idempotent.

chore(qa): Small changes suggested in PR #222

---

.eslintrc.js
codecept.conf.js
suites/bdd/features/sample/sample.feature
suites/bdd/step_definitions/executable/executable.js
suites/bdd/step_definitions/sample/sample.js

BDD (Gherkin) syntax can be used to design executable tests. Create them under suites/bdd

enable creation of executable tests in bdd

---

suites/pre-release/dcf/5.oidcFlowTest.js

forgot to add a @manual tag here.

fix(qa): Scenario missing @manual tag

---

suites/dream-challenge/DCgen3clientTest.js
suites/pre-release/dcf/5.oidcFlowTest.js

Blocking qa-dcp release testing

fix(qa): Missing manual tag

---

suites/portal/terraExportWarningTestPlan.js

Adds a test plan for Terra Export Warning feature (https://ctds-planx.atlassian.net/browse/PXP-5186)
Corresponding Portal PR: https://github.com/uc-cdis/data-portal/pull/642

Add executable test plan for Terra Export Warning

---

suites/apis/dataStageOIDCFlowTest.js

Fixing bugs to facilitate executable tests.

fix(qa): Bug fixes for BDCat executable tests

---

run-tests.sh
services/portal/home/homeProps.js
services/portal/home/homeSequences.js
services/portal/home/homeTasks.js
suites/portal/exportToWorkspaceTest.js
suites/portal/homepageTest.js
test_list.txt

Updated login test to use the Login button added to top bar

changed login test to support top bar Login button

---

run-tests.sh

Annotation topBarLogin in run-tests.sh

fixing annotation in run-tests.sh for topBarLogin

---

suites/sheepdogAndPeregrine/submitAndQueryNodesTest.js

The scenario "'submit data node with consent codes @indexRecordConsentCodes'" is blocking DCF PRs due to some mysterious behavior where only the very 1st iteration of this scenario fails.
Currently, we did not find a way to reproduce this issue.
Trying to delete lingering indexd records and retrying the entire Feature as a mitigation to this bizarre behavior.

chore(qa): Delete lingering indexd records before Sheepdog test + retries

---

package-lock.json
package.json

Bumping up the version of some dependencies to address security alerts.

chore(qa): bumping up the version of dependencies

---

package-lock.json
package.json
suites/apis/dcfsMetadataServiceTest.js

This PR contains an initial draft for the executable tests related to the upcoming DCF Metadata Service.
All http interactions are currently mocked as the service hasn't been deployed to a test environment yet.

task(qa): Executable tests for metadata service

---

package-lock.json
package.json

1 minimist vulnerability found in package-lock.json 2 days ago

chore(qa): Address security alert related to minimist

---

hooks/test_results.js
run-tests.sh

Revert "chore(qa): Skip DRS tests if DRS is not deployed"

---

suites/apis/dataStageOIDCFlowTest.js

Make sure there are links for contact form, accessibility, NIH, privacy policy, etc.

task(BDCat): Introduce new test scenarios to check required hyperlinks/pages

---

load-testing/fence/presigned-url.js
load-testing/indexd/indexdLTUtils.js
load-testing/load-test-descriptor-sample.json
load-testing/loadTestRunner.js

Better approach to randomly select indexd GUIDs (based on an arbitrary ACL).

chore(load tests): pick up random guids based on ACL lookup

---

suites/apis/dataStageOIDCFlowTest.js

Thanks to @mpingram , this feature is ready to be tested in bdcat preprod:
https://ctds-planx.atlassian.net/browse/PXP-5661

task(bdcat): Enable Privacy Policy test

---

suites/pre-release/dcf/1.linkAccountsTest.js
suites/pre-release/dcf/2.serviceAccountsRegistrationTest.js
suites/pre-release/dcf/3.googleCredentialsTest.js
suites/pre-release/dcf/4.preSignedURLTest.js
suites/pre-release/dcf/5.oidcFlowTest.js
suites/pre-release/dcf/6.indexdTest.js
utils/apiUtil.js

Fixing minor async issues, chai.expect imports, undefined variables, correcting features numbering, etc.

chore(qa): Minor updates to DCF tests (refactoring)

---

run-tests.sh
services/portal/home/homeProps.js
utils/apiUtil.js

Stop force-merging ppl.
Let us improve our tests to adapt to new environments.

fix(covid19): Fix login test to xpath-select custom homepage elements

---

README.md
check-pod-health.sh
codecept.conf.js

To be merged after the steps from:
> DO NOT MERGE BEFORE TESTING: chore(qa): Update selenium/standalone-chrome sidecar img
https://github.com/uc-cdis/cloud-automation/pull/1174
Are applied.

REQUIRES JENKINS WITH SELENIUM 4 SIDE CAR: chore(qa): Updating config for compatibility with Selenium 4

---

README.md
check-pod-health.sh
codecept.conf.js

Revert "chore(qa): Updating config for compatibility with Selenium 4"

---

run-tests.sh

This PR labeling option should facilitate retries against specific test suites.

chore(qa): Always set @reqGoogle for label-based retries

---

suites/apis/dataUploadTest.js
utils/dataUpload.js

Whenever the data upload tests fail intermittent, the overall PR time goes beyond 1.5 hs.
Hopefully these changes will, at least, allow us to fail faster and make room for more PR checks to be executed throughout the day.

chore(qa): Fail faster on data upload tests

---

run-tests.sh
suites/fail.js

Revert "chore(qa): Fail PR Check if Zero tests are executed"

---

run-tests.sh
suites/fail.js

This is required to address the issue where some bad labels could be accidentally set and skip all tests.

chore(qa): Fail PR Check if Zero tests are executed

---

run-tests.sh
suites/fail.js

fix(qa): Determine zero tests correctly

---

services/portal/home/homeTasks.js

Mitigation for covid19 portal bug.

chore(qa): Trigger additional homepage refresh for covid19 pages

---

run-tests.sh

Jira Ticket: n/a
- Add optional fourth arg to runTestsIfServiceVersion, for specifying a version in monthly release (2020.xx) format alongside its conventional semver sibling. If fourth arg present and currentVersion is ge 2020, the check will compare against the fourth arg. Fixes the "RUNNING someTestSuite bc 2020.x is greater than 3.2.1" problem.

fix(release-version-check)

---

services/apis/drs/drsQuestions.js

some console.logs

---

Jenkinsfile

just testing GCP keys deletion

---

Jenkinsfile

Revert "just testing GCP keys deletion"

---

services/portal/home/homeQuestions.js
services/portal/login/loginQuestions.js

Facing browser timeouts for qa-covid19 & chicagoland.pandemicresponsecommons.org PRs.

chore(qa): Increase timeout to check name of the loggedin user

---

services/apis/indexd/indexdTasks.js

Don't try to delete indexd records if HTTP GET query returns 404 Not Found.

chore(qa): Improve centralizedAuth test logic

---

grafana_test_observability.json
hooks/test_results.js

Set hardcoded `prName` and `repoName`.
Rename Grafana dashboard json file and correct data source ref.
Result:

chore(qa): Set hardcoded pr number and repo name for local CI Metrics monitoring

---

suites/pre-release/dcf/2.serviceAccountsRegistrationTest.js

Small tweaks for DCF executable tests.

fix(qa): Fix camel-case variables for DCF executable tests

---

README.md
publish-test-reports.sh
suites/google/googleServiceAccountKeyTest.js
utils/commanders/sshk8s.js

Removing `set -i` from various scripts due to the Ubuntu 18 upgrade.

chore(qa): Remove set -i due for bash 4.4 compatibility

---

README.md
check-pod-health.sh
codecept.conf.js
hooks/test_results.js
package-lock.json

Experimenting with Selenium 4 to check if that addresses some of the intermittent issues we have been facing.

chore(qa): Try selenium4 again

---

README.md
check-pod-health.sh
codecept.conf.js
hooks/test_results.js
package-lock.json

Revert "chore(qa): Try selenium4 again"

---

codecept.conf.js

Applying this change as per:
https://github.com/theintern/intern/issues/878
https://developers.google.com/web/updates/2017/04/headless-chrome

chore(qa): Tweak webdriver config

---

run-tests.sh

Small fix for a sheepdog-labeled PRs.

fix(qa): Do not run @indexRecordConsentCodes scenarios when the submitAndQueryNodesTest label is applied

---

run-tests.sh
suites/apis/metadataIngestionTest.js
suites/portal/indexingPageTest.js
utils/apiUtil.js

Jira Ticket: [PXP-6276](https://ctds-planx.atlassian.net/browse/PXP-6276)
This Pull Request comprises the automated integration tests for the `ingest-metadata-manifest` & `get-dbgap-metadata` sower jobs -- which instrument the dbgap extract script (https://github.com/uc-cdis/dbgap-extract) and the metadata service (https://github.com/uc-cdis/metadata-service).
[https://github.com/uc-cdis/gen3-qa/blob/master/docs/testplans/sower-jobs/metadata-ingestion-test-plan.md](https://github.com/uc-cdis/gen3-qa/blob/master/docs/testplans/sower-jobs/metadata-ingestion-test-plan.md)
- New tests for the metadata ingestion sower jobs.
These tests rely on new artifacts that were placed in the `cdis-presigned-url-test` S3 bucket:
- `test-study-subject-id.tsv`
- `phs000200.v12.p3.xml`

task(qa): Metadata Ingestion CI tests

---

docs/testplans/sower-jobs/metadata-ingestion-test-plan.md

Small change to describe the test scenarios more accurately.

doc(qa): Expand metadata ingestion test plan based on latest changes

---

package-lock.json
package.json
suites/portal/indexingPageTest.js
utils/apiUtil.js

Addressing all issues pointed out by the linter (eslint).

chore(qa): Refactor apiUtils

---

services/apis/fence/fenceTasks.js
suites/apis/metadataIngestionTest.js
suites/google/googleDataAccessTest.js
suites/portal/indexingPageTest.js
utils/apiUtil.js
utils/google.js

Simple refactor for google tests again

Chore(qa): Simple refactor for google tests again

---

.secrets.baseline
services/portal/dataUpload/dataUploadQuestions.js
utils/apiUtil.js

Small tweaks to avoid failures caused by prematurely giving up on checks based on waiting or polling.

chore(qa): Increase timeouts for a few tests

---

services/apis/fence/fenceTasks.js
utils/google.js

This doesn't seem to help and it is taking too long to reach the end of the PR check.
Reverts uc-cdis/gen3-qa#397

Revert "chore(qa): Wait a bit more for a 403 AccessDenied from Google Storage API call"

---

docs/testplans/obj-mgmt-api/obj-mgmt-api-test-plan.md

Jira Ticket: [PXP-5974](https://ctds-planx.atlassian.net/browse/PXP-5974)
Test Plan for the Object Management API feature.

doc(qa): Test Plan for Object Management API

---

.secrets.baseline
suites/google/googleDataAccessTest.js
utils/google.js

Small tweak to try to improve stability.

chore(qa): GoogleDataAccessTest - Move usersync to before block

---

services/apis/fence/fenceTasks.js
utils/apiUtil.js

Sometimes Fence returns a http 503 service unavailable (probably due to a surge of requests produced by the automation flow), if that happens the test should retry the request.

fix(qa): Import sleepMS into fenceTask

---

suites/google/googleDataAccessTest.js

fix(qa): Run one final usersync after the last google data access test scenario

---

docs/testplans/bucket-manifest/bucket-manifest-test-plan.md

Jira Ticket: [PXP-6372](https://ctds-planx.atlassian.net/browse/PXP-6372)
New test plan for the `bucket manifest generation` feature.

doc(qa): Test Plan for Bucket Manifest Generation

---

services/apis/fence/fenceProps.js

Fix for:
```
code: 404,
errors:
[ ******** message:
'Service account projects/gen3qa-ci-env-1-279903/serviceAccounts/service-account@gen3qa-ci-env-1.iam.gserviceaccount.com does not exist.',
domain: 'global',
reason: 'notFound' } ] }
Error: 404
```

fix(qa): Allow override of google service account's prj id

---

docs/testplans/bucket-manifest/bucket-manifest-test-plan.md
package-lock.json
package.json
run-tests.sh
suites/batch/bucketManifestGenerationTest.js

Jira Ticket: [PXP-6373](https://ctds-planx.atlassian.net/browse/PXP-6373)
This PR introduces the new CI test for the Bucket Manifest Generation feature.
Which is executed by a Jenkins2 job on a daily basis and sends results to Slack.
- New CI test for the Bucket Manifest Generation feature

task(qa): CI tests for bucket manifest generation

---

suites/batch/bucketManifestGenerationTest.js

@batch tests are not supposed to run as part of PR checks.

fix(qa): Annotate bucketManifestGenerationTest with @batch

---

jenkins-simulate-data.sh

tracking data simulator success and failures in influxdb.

chore(qa): Write metrics for data simulator

---

run-tests.sh

fix(qa): Setting correct conditions for AuthN tests

---

.github/workflows/automerge.yml

add automerge gh action to gen3-qa

---

.secrets.baseline
codecept.conf.js
suites/apis/cleverSafeTest.js

The asynchronous function wasn't reaching the axios GET request and the assertion so this test has been producing false positives 🤦 
- Replace Axios GET request with proper CodeceptJS `I.sendGetRequest` instruction.
**BLOCKED BY**: https://github.com/uc-cdis/cloud-automation/pull/1377

fix(qa): Fix CleverSafe test

---

files/qa_reports_landing_page/script.js
publish-test-reports.sh

Fixing Quarter filters in QA Reports landing page.

fix(qa): Fix quarter filter on QA reports landing page

---

docs/testplans/study-viewer/study-viewer.md
load-testing/loadTestRunner.js

Addition of Test plan for Study Viewer feature

testPlans : study-viewer

---

load-testing/loadTestRunner.js
suites/portal/studyViewerTest.js

Tests for Study Viewer Feature

test : adding tests for study viewer

---

docs/testplans/study-viewer/study-viewer.md

- Add multiple study viewers scenario to test plan

Add multiple study viewers scenario to test plan

---

suites/apis/dataUploadTest.js
utils/nodes.js

debug(qa): Debugging data file upload test

---

utils/commanders/sshk8s.js

Small tweak for local test runs to work more seamlessly.

Chore(qa): set default kubeconfig path

---

load-testing/loadTestRunner.js

Change the ouput from `--out json` to `--summary-reports`

chore : output to summary reports

---

utils/nodes.js

chore(qa): Debug data file upload test

---

services/portal/dataUpload/dataUploadProps.js

- Change classnames in data upload tests to work with new version or portal. (Will continue to work with old versions of portal).

Fix classnames of tests to work with new version of portal

---

run-tests.sh

chore(ci): Disable RAS tests (hopefully just temporarily)

---

suites/portal/homepageTest.js

Tiny change to assist with future troubleshooting efforts.

chore(qa): Add screenshot to homepageTest

---

jenkins-simulate-data.sh

- Use latest poetry for jenkins-data-sim

fix: use latest poetry

---

.github/workflows/automerge.yml
docs/testplans/environment-specific/dataguidsorg-test-plan.md

- Add test plan for dataguid.org

Add test plan for dataguid.org

---

suites/access/accessGUITest.js

Jira Ticket: [PXP-6822](https://ctds-planx.atlassian.net/browse/PXP-6822)
Automated GUI tests with Executable Test prompts to quickly run all user flows for both Super Admin & Admin users:
https://github.com/uc-cdis/cdis-wiki/blob/master/product/rough_ACCESS_test_plan.md#super-admin-add-admin
- New GUI tests.

task(qa): Access GUI tests

---

.secrets.baseline
run-tests.sh
services/apis/mariner/marinerProps.js
suites/mariner/marinerIntegrationTest.js
suites/mariner/workflows/no_input_test/request_body.json
suites/mariner/workflows/no_input_test/workflow/cwl/expressiontool_test.cwl
suites/mariner/workflows/no_input_test/workflow/cwl/gen3_test.cwl
suites/mariner/workflows/no_input_test/workflow/cwl/initdir_test.cwl
suites/mariner/workflows/no_input_test/workflow/cwl/scatter_test.cwl
suites/mariner/workflows/no_input_test/workflow/cwl/subworkflow_test.cwl
suites/mariner/workflows/no_input_test/workflow/inputs.json
suites/mariner/workflows/no_input_test/workflow/workflow.json
utils/marinerUtil.js
utils/user.js

First cut of mariner integration tests

Mariner tests - first cut

---

jenkins-simulate-data.sh

Retry in case we face poetry install issues:
```
1  ~/.poetry/lib/poetry/_vendor/py3.6/cachecontrol/adapter.py:53 in send
resp = super(CacheControlAdapter, self).send(request, **kw)
ConnectionError
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
at ~/.poetry/lib/poetry/_vendor/py3.6/requests/adapters.py:498 in send
494│                     low_conn.close()
495│                     raise
496│ 
497│         except (ProtocolError, socket.error) as err:
→ 498│             raise ConnectionError(err, request=request)
499│ 
500│         except MaxRetryError as e:
501│             if isinstance(e.reason, ConnectTimeoutError):
502│                 # TODO: Remove this in 3.0.0: see #2811
```

chore(qa): Retry poetry install in case of any connectivity failures

---

services/portal/dataUpload/dataUploadSequences.js
suites/portal/dataUploadTest.js

chore(qa): Take screenshots to debug portal-dataUploadTest

---

suites/gen3-client/gen3clientTest.js

Adding a new scenario:
```
Scenario('Try the download-multiple feature @manual'
```
This should be ported to a fully automated test later.

chore(qa): Fix eslint issues and add a new scenario to test download-multiple

---

docs/testplans/hatchery/hatchery-executable-test-plan.md
docs/testplans/hatchery/hatchery-executable-test-plan.md~

Jira Ticket: [PXP-4946](https://ctds-planx.atlassian.net/browse/PXP-4946)
Develop a Hatchery executable test plan

doc(qa): Develop a Hatchery executable test plan

---

suites/apis/presignedUrlTest.js
suites/sheepdogAndPeregrine/submitAndQueryNodesTest.js

Trying to debug (or, potentially fix) this PR check failure here:
https://github.com/uc-cdis/cdis-manifest/pull/2324

chore(qa): Debug sheepdog tests due to failure in a dcf staging PR

---

docker-compose-test-infra.yaml

Selenium 4 requires new config for docker / local runs.

chore(qa): Tweak docker-compose for selenium4

---

jenkins-simulate-data.sh

fix(qa): tweak data simulation based on tested env

---

jenkins-simulate-data.sh
services/apis/sheepdog/sheepdogTasks.js
utils/nodes.js

Motivation: To handle the edge case in MIDRC DD that uses a file node called `imagina_data_file`.

chore(qa): Identifying all DD file nodes with '_file'

---

run-tests.sh

Revert "chore(ci): Disable RAS tests (hopefully just temporarily)"

---

suites/portal/landingPageButtonsTest.js

Jira Ticket: [PXP-6216](https://ctds-planx.atlassian.net/browse/PXP-6216)
Create automated tests for Landing Page buttons.
- Check if landing page cards & buttons exist, if they do, click and run assertions on expected URLs.
DEPENDS ON: https://github.com/uc-cdis/gitops-qa/pull/1056
Checklist:

task(qa): Test landing page buttons (requires CodeceptJS 3)

---

suites/apis/etlTest.js

Printing timestamps and tracking the time to run etl test scenarios.

chore(qa): Track ETL Job execution time

---

run-tests.sh
suites/portal/dataguidOrgTest.js

Tiny fix for dataguids.org tests.

fix(qa): Use correct jenkins namespace for dataguids.org test

---

utils/apiUtil.js

Debugging how the homepageTest is adapting to different css locators based on the `testedEnv` env. variable.

chore(qa): Debug getHomePageDetails

---

hooks/test_results.js

Refactoring and adding new metric: `test.duration`.
- Tracking duration of tests to prioritize which ones need to be re-engineered or parallelized.

chore(qa): Track duration of tests in our CI Metrics.

---

utils/apiUtil.js

Fixing Gen3Response constructor that was accidentally modified in https://github.com/uc-cdis/gen3-qa/pull/518

fix(ci): Fixing Gen3Response constructor ASAP

---

Dockerfile

Quick change to copy folders correctly.

chore(qa): Add gen3-qa folders to Docker img correctly

---

Dockerfile
suites/google/checkAllProjectsGoogleBucketAccessTest.js

Jira Ticket: [PXP-7308](https://ctds-planx.atlassian.net/browse/PXP-7308)
This change supports the following PR: https://github.com/uc-cdis/cloud-automation/pull/1474

chore(qa): While running tests in PROD-tier absorb access token from env variable

---

package-lock.json
package.json
suites/google/checkAllProjectsGoogleBucketAccessTest.js

The previous module is not compatible with k8s jobs.

chore(qa): New progress bar for gen3qa-run checks

---

run-tests.sh

Disabling RAS tests in our CI Pipeline due to RAS Staging maintenance.

chore(qa): Disable RAS tests temporarily

---

suites/portal/coremetadatapageTest.js

add debugging to coremetadata test

debug: screenshot for coremetadata tests

---

suites/portal/dataUploadTest.js

Adding retries to avoid intermittent failures / flaky test noise.

chore(ci): Add retries to data upload test

---

services/apis/fence/fenceSequences.js
suites/google/googleServiceAccountKeyTest.js

chore(qa): Improve check and debugging for googleServiceAccountKeyTest

---

suites/portal/dataUploadTest.js
utils/apiUtil.js

Adding some polling logic and debugging lines to investigate intermittent data upload test failures.

chore(qa): Debugging the data upload file test (s3 upload)

---

docker-compose-test-infra.yaml
suites/pre-release/dcf/1.linkAccountsTest.js
suites/pre-release/dcf/2.serviceAccountsRegistrationTest.js

fix(dcf): Set healthy selenium images for docker-compose and remove duplicate scenarios from dcf executable tests

---

jenkins-simulate-data.sh

* avoid re-installing poetry
* avoid re-installing poetry

fix(simulate-data): poetry handling

---

suites/portal/homepageTest.js

Small mitigation (hopefully temporary) to unblock the access clinical data NIAID PRs.

chore(qa): Retry home page test

---

run-tests.sh

Revert "chore(qa): Disable RAS tests temporarily"

---

suites/pre-release/http302/fullQARoutine.js

Kudos to @ZakirG for this new feature and for the testing code as well 😄

chore(qa): Add bdcat test for new AND/OR filter feature

---

jenkins-simulate-data.sh

This is a temporary measure to upgrade pip before we can upgrade pip within the Jenkins image here: 
https://github.com/uc-cdis/cloud-automation/blob/master/Docker/Jenkins/Dockerfile

chore(qa): Upgrade pip before generating data

---

load-testing/indexd/create-indexd-records.js
load-testing/loadTestRunner.js
load-testing/sample-descriptors/load-test-create-indexd-records.json

task(qa): Load testing script to create tons of indexd records

---

suites/batch/S3BucketManifestGenerationTest.js

fix(bucket-manifest-ci): remove codeceptjs3 curly-bracket notation added by accident

---

suites/portal/dataUploadTest.js

fix(qa): skip submission page check for midrc data upload flow

---

suites/portal/dataUploadTest.js

fix(qa): skip submission page check for midrc

---

run-tests.sh

chore(ci): Experimenting with Moon

---

utils/apiUtil.js

fixing homepage test for jenkins-niaid

fix: Homepage test for niaid

---

services/portal/home/homeTasks.js

qa(fix): wait page fully loaded before screenshot

---

run-tests.sh

Disabling the RASAUTHN test for now
https://cdis.slack.com/archives/CT2UNCWNB/p1616442104001600

disabling the RASAuthN tests

---

run-tests.sh

Disabling Study Viewer test
https://jenkins.planx-pla.net/blue/organizations/jenkins/CDIS_GitHub_Org%2Ffence/detail/PR-885/5/tests for debugging

disabling StudyViewertest

---

docker-compose-test-infra.yaml

updating influxdb version in docker-compose.yaml

---

grafana_test_observability.json

Updating ci-metrics dashboard JSON so any user can visualize the new panels.

chore(ci-metrics): Update observability dashboard

---

files/jenkins-job-create-testing-image-for-external-contributors.sh

New utility script.
- New utility script to create a copy of forked-repo branches to support the CI of open source contributions

chore(open-source): Create a copy of forked-repo branches to support the CI of open source contributions

---

.secrets.baseline
run-tests.sh
services/apis/requestor/requestorTasks.js
services/portal/studyViewer/studyViewerProps.js
services/portal/studyViewer/studyViewerTasks.js
suites/portal/studyViewerTest.js

Jira Ticket: [PXP-7485](https://ctds-planx.atlassian.net/browse/PXP-7485)
Adding new test scenarios to study viewer suite

second iteration of study-viewer tests

---

suites/portal/homepageTest.js

Adding selenium session count logging to home page test

adding session count logging to homepage test

---

load-testing/fence/synapse-fence.js
package.json
services/apis/drs/drsProps.js
services/apis/drs/drsTasks.js
services/apis/fence/fenceProps.js
services/apis/indexd/indexdTasks.js
services/apis/peregrine/peregrineSequences.js
services/apis/pidgin/pidginQuestions.js
suites/apis/dcfsMetadataServiceTest.js
suites/batch/S3BucketManifestGenerationTest.js
suites/fail.js
suites/portal/terraExportWarningTestPlan.js
utils/commanders/docker.js
utils/commanders/null.js
utils/interactive.js

Added parameter --fix to eslint script and executed it. Motivated by the travis build error - https://travis-ci.com/github/uc-cdis/gen3-qa/builds/223471685

added --fix and executed it

---

services/apis/manifestService/manifestServiceTasks.js

debugging exportToWorkspaceTest

debug(manifestservice): Additional debugging for exportToWorkspaceTest

---

docs/testplans/study-viewer/study-viewer.md

Addition of more scenarios in the test plan like testing multiple datasets and more detailed steps while requesting access to study dataset

updating the test plan for study viewer tests

---

suites/portal/dataUploadTest.js

Fix: delete files uploaded by metadataIngestionTest

---

suites/apis/dcfDataReplicationTest.js

fix test name

---

publish-test-reports.sh

Parametrize qa_user to enable publishing reports to different qa commons

parametrize qa_user

---

suites/pre-release/heal/e2e.js

Manual e2e discovery page test for pre-release testing

added a manual e2e test for pre-release testing

---

publish-test-reports.sh

fix publish reports

---

docs/testplans/sower-jobs/metadata-ingestion-test-plan.md

Small test plan update for mds.

doc(qa): Update MDS Test Plan

---

run-tests.sh

Let us re-enable RAS tests for our CI Pipeline.

chore(ci): Re-enable RAS Integration tests

---

utils/apiUtil.js

Added properties for HEAL bundle where the home page is actually the Discovery page

update home page test for heal bundle

---

codecept.conf.js
run-tests.sh
services/portal/home/homeTasks.js

Revert "Chore/test heal without moon"

---

run-tests.sh

Jira Ticket: [PXP-7807](https://ctds-planx.atlassian.net/browse/PXP-7807)
- Do not run audit-service tests if version <1.0.0

PXP-7807 Do not run audit-service tests if version <1.0.0

---

jenkins-simulate-data.sh

- Log simulated data to facilitate debugging

Log simulated data to facilitate debugging

---

suites/portal/pfbExportTest.js

fix(pfb-export-test): Use sequencing node when testedEnv includes anvil

---

hooks/test_results.js
suites/portal/pfbExportTest.js

chore(ci): Tweak PFB Export test

---

Dockerfile
gen3.qa.in.a.box.codecept.conf.js
package-lock.json
package.json

Gen3 QA in a BOX.
The plan is to wrap this all up in a k8s job:
1. `docker run -it --net=host quay.io/cdis/gen3-qa-controller /bin/bash`
2. `cd ..`
3. `npx selenium-standalone install --version=4.0.0-alpha-7`
4. `timeout 120 npx selenium-standalone start --version=4.0.0-alpha-7 &`
5. `GEN3_SKIP_PROJ_SETUP=true RUNNING_LOCAL=true NAMESPACE=qa-dcp npm test -- --verbose suites/portal/homepageTest.js`

task(gen3-qa-in-a-box): Run tests within a container/pod with selenium-standlone

---

run-tests.sh

Change for studyViewer config in `run-tests.sh`  to fix and evaluate when the env is eligible for running the studyViewer test

fix : to evaluate the env for eligibility for running the test

---

suites/portal/homepageTest.js

Jira Ticket: [PXP-8563](https://ctds-planx.atlassian.net/browse/PXP-8563)
- Save a screenshot of the home page right after logging in.

chore(homepageTest): save screenshot after login.

---

utils/apiUtil.js

Relatd to https://github.com/uc-cdis/cdis-manifest/pull/3332 for [HP-291](https://ctds-planx.atlassian.net/browse/HP-291), [HP-320](https://ctds-planx.atlassian.net/browse/HP-320)
* Handle BRH and HEAL UIs using discovery as their home page

fix(tests): tests for BRH, HEAL

---

docs/testplans/ras/visa-update-cronjob.md

doc(ras-m2): Visa Update Cronjob

---

run-tests.sh
services/apis/mds/mdsTasks.js
services/portal/discovery/discoveryQuestions.js
suites/portal/discoveryPageTest.js

Jira Ticket: [HP-348](https://ctds-planx.atlassian.net/browse/HP-348)

changes for Agg MDS

---

run-tests.sh

fix aggmds check in run-tests

---

hooks/test_results.js
services/portal/discovery/discoveryTasks.js
suites/portal/discoveryPageTest.js

fix disco page for agg mds

---

run-tests.sh

adding monthly version check to run agg mds tests

---

suites/apis/rasIntegrationTest.js

Due to policy reasons we're no longer allowed to provide RAS visas. [PR coming soon](https://github.com/uc-cdis/fence/pull/956) for fence to remove visas. In the mean time, removing the checks
- Remove ga4gh visa checking in userinfo. No longer Providing RAS visas in userinfo.

Remove Visa Check

---

run-tests.sh

Jira Ticket: [HP-348](https://ctds-planx.atlassian.net/browse/HP-348)
Logic to run tests for discovery page

fix logic for discovery page

---

codecept.conf.js
gen3.qa.in.a.box.codecept.conf.js

changing the webdriver url from `https://${process.env.HOSTNAME}` to `https://${process.env.NAMESPACE}.planx-pla.net`

Updating the WebDriver URL

---

utils/commanders/k8s.js

- Make K8s.runCommand error message more clear

Make K8s.runCommand err msg more clear

---

Jenkinsfile
hooks/test_results.js
run-tests.sh

Gauge for test duration and counters for pass & fail counts
- Sending metrics to DataDog properly

fix(ci-metrics): Gauge for test duration and counters for pass & fail counts

---

services/apis/mds/mdsTasks.js

use kube job for agg mds sync

---

run-tests.sh

version for kube job to sync agg mds

---

services/apis/auditService/auditServiceTasks.js

See https://github.com/uc-cdis/cloud-automation/pull/1643
- Fix audit tests: Fence deployment now has a single container

Fix audit tests: Fence deployment now has a single container

---

suites/portal/pfbExportTest.js

chore(pfb-test): Other pfb test improvements

---

.vscode/launch.json
services/portal/exportToWorkspace/exportToWorkspaceSequences.js
services/portal/exportToWorkspace/exportToWorkspaceTasks.js
services/portal/home/homeSequences.js
services/portal/home/homeTasks.js
services/portal/indexing/indexingTasks.js
suites/apis/OAuth2Test.js
suites/apis/auditServiceTest.js
suites/portal/coremetadatapageTest.js
suites/portal/dataUploadTest.js
suites/portal/discoveryPageTest.js
suites/portal/exportToWorkspaceTest.js
suites/portal/homepageTest.js
suites/portal/indexingPageTest.js
suites/portal/landingPageButtonsTest.js
suites/portal/loginPageTest.js

Handle data use agreement popup in the login action

handle data use popup

---

suites/apis/aggMDSTest.js
suites/portal/discoveryPageTest.js

- AggMDS tests should `await` on `async` job to finish

fix: wait on aggmds sync job

---

services/apis/auditService/auditServiceTasks.js

Fix fence pod connection issue in audit service tests
> Error
> Unexpected token ² in JSON at position 0

check if pods are terminating

---

services/portal/exportToWorkspace/exportToWorkspaceTasks.js
services/portal/home/homeSequences.js
services/portal/home/homeTasks.js
suites/apis/auditServiceTest.js
suites/portal/coremetadatapageTest.js
suites/portal/dataUploadTest.js
suites/portal/exportToWorkspaceTest.js
suites/portal/homepageTest.js

handle data user agreement popup in the logout action

handle popup message at logout

---

services/portal/home/homeProps.js
services/portal/home/homeTasks.js

The popup box of user agreement for MIDRC and VA have different text. To click the Accept button properly, change the code to find if there is a popup box contains the accept button.

check the popup box by the accept button

---

suites/apis/auditServiceTest.js
suites/apis/dbgapTest.js
suites/apis/drsEndpointsTest.js
suites/apis/linkGoogleAccountTest.js
suites/google/googleServiceAccountRemovalTest.js
suites/google/googleServiceAccountTest.js
suites/portal/pfbExportTest.js
suites/sheepdogAndPeregrine/submitFileTest.js

-  add/increase retries for commonly flaky tests

chore(retries): add/increase retries for commonly flaky tests

---

services/portal/home/homeQuestions.js

The change here is  ->
commenting out the cards check on commons homePage as not all the commons have cards

not checking the cards on homePage

---

suites/pre-release/dcf/prereq.md

Adding test execution and publishing the reports step to the document

chore: update the test execution steps for pre-release

---

gen3.qa.in.a.box.codecept.conf.js
run-tests.sh

Update chromedriver version

---

files/qa-reports/index.html

fix html and update the quarters to recent ones

---

.secrets.baseline
README.md

Made updates to main readme for setting up and running the project

docs/updateSetup: update setup and add prerequisites

---

suites/portal/discoveryPageTest.js

update test data with the new fields added

---

hooks/test_results.js

fix datadog cluster agent name

---

suites/portal/dataguidOrgTest.js

increase timeouts for dataguids tests

---

suites/portal/dataguidOrgTest.js

Increase timeout in dataguids test

---

Jenkinsfile
hooks/test_results.js
package-lock.json
package.json

testing datadog connection

---

load-testing/ga4gh/drs-performance.js
load-testing/loadTestRunner.js
load-testing/sample-descriptors/load-test-ga4gh-drs-performance-sample.json

relies on https://github.com/uc-cdis/gen3-release-utils/pull/162
- add mutual TLS support for DRS Performance testing

feat(mtls): add mtls support to drs performance test script

---

suites/portal/pfbExportTest.js

-  more logging to some tests for debugging

chore(pfbexport): add more logs to failing guppy mutation

---

gen3.qa.in.a.box.codecept.conf.js
hooks/test_results.js
run-tests.sh
services/portal/workspace/workspaceTasks.js
suites/apis/aggMDSTest.js
suites/apis/metadataIngestionTest.js
suites/portal/discoveryPageTest.js

heal e2e test with drs-pull in notebook

---

suites/pre-release/dcf/5.oidcFlowTest.js

`Error | RangeError: Invalid count value` resolved

fixing the nonce idtoken error

---

services/portal/workspace/workspaceTasks.js
suites/portal/discoveryPageTest.js

increase wait time for `Open in Workspace`

---

suites/portal/pfbExportTest.js

fail the test faster and with a more obvious error message
- PFB test: fail if the necessary file is not there

PFB test: fail if the necessary file is not there

---

suites/apis/etlTest.js

move etl test validation to the respective test

---

.secrets.baseline
load-testing/audit-service/audit-login.js
load-testing/audit-service/audit-presigned-url.js
load-testing/fence/presigned-url.js
load-testing/fence/service-account-patch.js
load-testing/fence/synapse-fence.js
load-testing/ga4gh/drs-performance.js
load-testing/indexd/create-indexd-records.js
load-testing/indexd/drs-endpoint.js
load-testing/loadTestRunner.js
load-testing/metadata-service/create-and-query.js
load-testing/metadata-service/filter-large-database.js
load-testing/portal/study-viewer.js
load-testing/sheepdog/export-clinical-metadata.js
load-testing/sheepdog/import-clinical-metadata.js

add tags for load tests

---

services/apis/etl/etlProps.js
services/apis/etl/etlQuestions.js
services/apis/etl/etlTasks.js
suites/apis/etlTest.js
suites/portal/pfbExportTest.js

Jira Ticket: [PXP-9639](https://ctds-planx.atlassian.net/browse/PXP-9639)
- Clean up ES indices after ETL and PFB Export tests

(PXP-9639): Clean up Elasticsearch indices after ETL and PFB export tests

---

load-testing/loadTestRunner.js

await for generateLib

---

load-testing/audit-service/audit-login.js
load-testing/audit-service/audit-presigned-url.js
load-testing/fence/presigned-url.js
load-testing/fence/service-account-patch.js
load-testing/fence/synapse-fence.js
load-testing/ga4gh/drs-performance.js
load-testing/indexd/create-indexd-records.js
load-testing/indexd/drs-endpoint.js
load-testing/metadata-service/create-and-query.js
load-testing/metadata-service/filter-large-database.js
load-testing/portal/study-viewer.js
load-testing/sheepdog/export-clinical-metadata.js
load-testing/sheepdog/import-clinical-metadata.js

use test_scenario as the tag

---

load-testing/loadTestRunner.js

remove duplicate code from loadtestrunner

---

suites/apis/rasCronjobValidate.js

Adding executable tests for validating `fence-visa-update` cronjob

adding executableTests for ras cronjob validation

---

suites/apis/rasDRSTest.js

fixing RAS before suite to fix jenkins build

fix: ras test before suite

---

run-tests.sh

disabling the test till debugging the tests in CI pipeline

disabling studyViewer test (for now)

---

load-testing/dicom-server/metadata.js
load-testing/dicom-viewer/study.js
load-testing/loadTestRunner.js
load-testing/loadTestRunnerV2.js
load-testing/sample-descriptors/load-test-dicom-server-metadata.json
load-testing/sample-descriptors/load-test-dicom-viewer-study.json

dicom load tests on jenkins2

---

hooks/test_conditions.js
suites/portal/registerUserTest.js

Skip registerUser test if loginfordownload or dropdown not configured in gitops.json

Add test condition to register user tests

---

suites/apis/dataUploadTest.js
suites/apis/dbgapTest.js
suites/portal/pfbExportTest.js
suites/portal/registerUserTest.js
suites/portal/studyViewerTest.js

adding `@e2e` to the test suites

add @e2e annotation to tests

---

run-tests.sh

while fixing the test flow which seems incorrect now

Disable study viewer tests

---

services/apis/requestor/requestorTasks.js
suites/portal/studyViewerTest.js

- Study viewer: wait before checking the request

Study viewer: wait before checking the request

---

load-testing/ga4gh/drs-performance.js

- Fix pagination bug when fetching guids in `load-testing/ga4gh/drs-performance.js`

fix(drs-performance.js): pagination bug

---

services/apis/etl/etlTasks.js

Jira Ticket: [QAT-541](https://ctds-planx.atlassian.net/browse/QAT-541)

try to delete _0 indices always

---

suites/pre-release/http302/fullQARoutine.js

https://ctds-planx.atlassian.net/browse/QAT-573

fix acl json format

---

suites/apis/aggMDSTest.js

to support change in behavior where error is thrown when no records are synced, only commenting it out since this behavior may not be final

do not run agg mds sync after test run

---

run-tests.sh

- Describe what this pull request does.
- Add short descriptive bullet points for each section if relevant. Keep in mind that they will be parsed automatically to generate official release notes.
- Test manually.
- Maintain or increase the test coverage (if relevant).
- Update the documentation, or justify if not needed.
-->

disable the Test

---

run-tests.sh
services/portal/GWAS/GWASProps.js
services/portal/GWAS/GWASTasks.js
suites/portal/GWASUITest.js

Make sure to follow the DEV guidelines (https://gen3.org/resources/developer/dev-introduction/) before asking for review.
- Describe what this pull request does.
- Add short descriptive bullet points for each section if relevant. Keep in mind that they will be parsed automatically to generate official release notes.
- Test manually.
- Maintain or increase the test coverage (if relevant).
- Update the documentation, or justify if not needed.
-->

Gwas jenkins Enabled Test PR & Test Updates

---

run-tests.sh
services/portal/GWAS/GWASProps.js
services/portal/GWAS/GWASTasks.js
suites/portal/GWASUITest.js

Revert "Gwas jenkins Enabled Test PR & Test Updates"

---

suites/apis/metadataIngestionTest.js

exclude last scenario from metadataIngestionTest

---

services/apis/mds/mdsTasks.js
suites/apis/metadataIngestionTest.js

- Fix the `metadataIngestionTest` "create a new mds entry and then issue http delete against mds/objects/{guid}" by replacing the failing `sendDeleteRequest` with a `curl` command

Use bash+curl instead of sendDeleteRequest

---

suites/portal/discoveryPageTest.js

Get the summary field name dynamically from config

---

suites/apis/dbgapTest.js

debug dbgap tests

---

README.md
test-data/aggMDSTest/study2.json
test-data/aggMDSTest/study3.json

fix discoverypagetest

---

test-data/aggMDSTest/study1.json

Jira Ticker : [BRH-389](https://ctds-planx.atlassian.net/browse/BRH-389)
* Adding a new field `full_name` with the same value as `project_title`
[BRH-389]: https://ctds-planx.atlassian.net/browse/BRH-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new field in AggMDS metadata for BRH

---

run-tests.sh
services/apis/fence/fenceProps.js
services/apis/fence/fenceTasks.js
suites/apis/oidcClientTest.js

Jira Ticket: [PXP-10542](https://ctds-planx.atlassian.net/browse/PXP-10542)
- Client creds rotation test
[PXP-10542]: https://ctds-planx.atlassian.net/browse/PXP-10542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-10542 Client creds rotation test

---

docs/testplans/GWAS/GWAS++_test_plan.md

[GQE-27](https://ctds-planx.atlassian.net/browse/GQE-27)
[GQE-27]: https://ctds-planx.atlassian.net/browse/GQE-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GWAS++ Test plan

---

.gitignore
services/apis/mds/mdsTasks.js

update for MDS v3
-Update AggMDS related codes to make it work with MDS `3.0.0+`

fix for mds v3

---

helpers/cdisHelper.js

<teardown> Error | TypeError: Cannot read property 'stack' of undefined

Handle unneeded logs

---

services/portal/home/homeTasks.js

Try catch system use message popup existence

---

services/portal/home/homeTasks.js

Revert "Try catch system use message popup existence"

---

services/portal/home/homeSequences.js
services/portal/home/homeTasks.js
suites/portal/coremetadatapageTest.js

Fix systemUse at login

---

services/portal/coreMetadataPage/coreMetadataPageQuestions.js

- Do not look for core metadata citation on portal page. This is a temporary fix because the portal does not always display the new citation format, depending on the deployed version of portal/peregrine/pidgin

Do not look for core metadata citation on portal page

---

services/portal/coreMetadataPage/coreMetadataPageQuestions.js
services/portal/coreMetadataPage/coreMetadataPageTasks.js

- change core metadata page screenshot timing

change core metadata page screenshot timing

---

suites/apis/auditServiceTest.js

Disable audit service test that uses RAS login

Disable audit service test that uses RAS login

---

codecept.conf.js
gen3.qa.in.a.box.codecept.conf.js
run-tests.sh
services/apis/requestor/requestorService.js
suites/apis/oidcClientTest.js

Jira Ticket: [PXP-10910](https://ctds-planx.atlassian.net/browse/PXP-10910)
see fix in https://github.com/uc-cdis/fence/pull/1090
- Test that rotated client credentials have access
[PXP-10910]: https://ctds-planx.atlassian.net/browse/PXP-10910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PXP-10910 Test that rotated client credentials have access

---

docs/testplans/GWAS/GWAS++_test_plan.md
docs/testplans/GWAS/GWAS_results_app.md

Jira Ticket: [GQE-68](https://ctds-planx.atlassian.net/browse/GQE-68)
[GQE-68]: https://ctds-planx.atlassian.net/browse/GQE-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding test for GWAS results v2 app

---

.pre-commit-config.yaml
.secrets.baseline
services/apis/indexd/indexdTasks.js
suites/apis/oidcClientTest.js

closes #949
- Remove requestor dependency from client creds rotation test

Remove requestor dependency from client creds rotation test

---

run-tests.sh

Jira Ticket: [GQE-73](https://ctds-planx.atlassian.net/browse/GQE-73)
[GQE-73]: https://ctds-planx.atlassian.net/browse/GQE-73?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use the default `donot` logic for labeled PRs

---

Jenkinsfile
run-tests.sh

[GQE-71](https://ctds-planx.atlassian.net/browse/GQE-71)
[GQE-71]: https://ctds-planx.atlassian.net/browse/GQE-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use separate container for selenium

---

suites/portal/pfbExportTest.js

adding necessary label to test

---

run-tests.sh
suites/apis/auditServiceTest.js

Fix test tag for audit-service tests

---

run-tests.sh

Skip dataguids test conditionally

---

run-tests.sh

Remove unnecessary quotes

---

run-tests.sh

Fix run tests logic for unlabeled PRs

---

suites/coremetadata/getCoremetadataTest.js
suites/portal/coremetadatapageTest.js
suites/portal/dataUploadTest.js
suites/portal/discoveryPageTest.js
suites/portal/exportToWorkspaceTest.js
suites/portal/registerUserTest.js

Adding appropriate requires service labels to test

---

services/apis/fence/fenceSequences.js

Add getUserTokensWithClient_getConsentCode.png screenshot

---

suites/pre-release/dcf/1.linkAccountsTest.js

change of login instructions in dcf pre-release

---

suites/portal/studyRegistrationTest.js

adding manual tag to the test

---

suites/apis/auditServiceTest.js

Add requires-portal tag to audit service homepage test

---

suites/sheepdogAndPeregrine/submitAndQueryNodesTest.js

Add missing test tags

---

services/portal/exportToWorkspace/exportToWorkspaceSequences.js
services/portal/exportToWorkspace/exportToWorkspaceTasks.js
suites/portal/exportToWorkspaceTest.js

enabling hatchery test scenario

---

run-tests.sh

Don't skip pfbExport test for pelican PRs

Don't skip pfbExportTest for pelican PRs

---

run-tests.sh

Fix run-tests for pfbExport

---

load-testing/indexd/indexdLTUtils.js
load-testing/sample-descriptors/load-test-presigned-url-bottleneck-sample.json

Jira Ticket: [GQE-118](https://ctds-planx.atlassian.net/browse/GQE-118)
[GQE-118]: https://ctds-planx.atlassian.net/browse/GQE-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fixing the presigned url load test

---

hooks/test_conditions.js

chore: add test conditions for exportToWorkspace tests

---

load-testing/sample-descriptors/load-test-create-indexd-records.json

edit  no of secs to run indexd test

---

run-tests.sh

enabling GWASUi Test for CI checks

---

utils/apiUtil.js

`heal` does not work since `chordshealth` also contains the string

fix summary identification

---

jenkins-simulate-data.sh

Data simulator now uses python 3.9, see https://github.com/uc-cdis/data-simulator/pull/99

Remove data-simulator python 3.8 line

---

jenkins-simulate-data.sh

Find leaf node in a generic way

---

run-tests.sh

Enable GWASUI tests

---

utils/apiUtil.js

- Print logs of failed pods after giving up

Print logs of failed pods after giving up

---

hooks/test_results.js

Jira Ticket: [GQE-158](https://ctds-planx.atlassian.net/browse/GQE-158)
[GQE-158]: https://ctds-planx.atlassian.net/browse/GQE-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update datadog host for CI observability

---

run-tests.sh

Run pfbExportTest for tube PRs as well

Run pfbExport tests for tube PRs

---

hooks/test_conditions.js

Jira Ticket: [GQE-171](https://ctds-planx.atlassian.net/browse/GQE-171)
[GQE-171]: https://ctds-planx.atlassian.net/browse/GQE-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix test condition hook for pfbExportTest

---

suites/apis/etlTest.js

CI tests are failing since ETL is not completed in 80 attempts (13 minutes)

Increase wait time for ETL.

---

hooks/test_conditions.js
run-tests.sh

Revert "Fix test condition for PFB Export tests"

---

run-tests.sh

Disabling GWAS test in CI

---

services/portal/home/homeProps.js
services/portal/home/homeTasks.js
services/portal/studyRegistration/studyRegistrationTasks.js
suites/portal/studyRegistrationTest.js

Update study registration tests

---

run-tests.sh

do not skip pfbexport test if repo is gitops-qa

---

suites/portal/gen3ffLandingPageTest.js

Run frontend-framework tests only in HEAL PRs

---

suites/portal/indexingPageTest.js

The indexing page test caught a bug for a fence change w.r.t presigned url generation

Run indexing page tests for fence PRs

---

suites/portal/GWASUIAppTest.js

Link to JIRA ticket if there is one: [GQE-262](https://ctds-planx.atlassian.net/browse/GQE-262)
[GQE-262]: https://ctds-planx.atlassian.net/browse/GQE-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GWAS Monthly Workflow Limit

---

suites/portal/pfbExportTest.js

Changes to support navbar changes done via [data-portal change](https://github.com/uc-cdis/data-portal/pull/1637)

Fix pfb export test for navbar changes

---

.secrets.baseline
docs/howto/authentication_file_phs001194.txt
docs/howto/google-data-access-tests.md
docs/testplans/non-DBGap_usersync/non-DBGap_usersync_testPlan.md
docs/testplans/sower-jobs/metadata-ingestion-test-plan.md
docs/testplans/study-viewer/study-viewer.md
files/test2_user.yaml
services/apis/fence/fenceProps.js
services/apis/sheepdog/sheepdogTasks.js
suites/access/accessGUITest.js
suites/apis/centralizedAuth.js
suites/apis/clientCredGrantTest.js
suites/apis/dbgapTest.js
suites/apis/nonDbgapUsersyncTest.js
suites/apis/rasDRSTest.js
suites/apis/requestorTest.js
suites/portal/pfbExportTest.js
suites/portal/studyViewerExportToWorkspaceTest.js
suites/portal/studyViewerTest.js
utils/user.js

Link to JIRA ticket if there is one: [GQE-310](https://ctds-planx.atlassian.net/browse/GQE-310)
[GQE-310]: https://ctds-planx.atlassian.net/browse/GQE-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update User Email ids

---

.github/workflows/lint.yaml
.pre-commit-config.yaml
.secrets.baseline
suites/portal/pfbExportTest.js

Fix syntax issue in pfbExportTest.js
